root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/hapi-lite ."
  bin = "./tmp/hapi-lite"
  exclude_dir = ["tmp", "web", "vendor"]
  exclude_regex = ["_test.go"]
  delay = 1000

[misc]
  clean_on_exit = true
